### ISSUE TITLE
Datasets and indexes files on Zenodo are inaccessible

### ISSUE THREAD

**Issue by weiwch** [matchyc/mysteryann#2]
I am very interested in your work and would like to reproduce your results. However, I do not have access to the files you have stored on Zenodo (e.g. https://zenodo.org/records/11073098/files/laion.query.10k.fbin in `prepare_data.sh` and https://zenodo.org/records/11090378/files/t2i_10M_roar.index?download=1). When I try to access these links, the page only displays 'Permission required. You do not have sufficient permissions to view this page.' Could you please confirm if the data is open-access? I have tried accessing with different accounts, but I receive the same message. Could you confirm if accounts other than yours can access the data?

**Comment by matchyc** [comment]
Thank you for your attention. To download files, please try this link: https://zenodo.org/records/11090378.

Please note that the main branch is deprecated. The competition version is on another branch, and the paper version is available at https://github.com/matchyc/RoarGraph.
